# Generated by Django 5.2.1 on 2025-05-13 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='credit_note_supplier',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='suppliers.supplier', verbose_name='Supplier'),
        ),
    ]
