# Generated by Django 5.2.1 on 2025-05-13 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Registered By'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_supplier',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Registered By'),
        ),
    ]
