# Generated by Django 5.2.1 on 2025-05-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditnote',
            options={'ordering': ['credit_note_reg_date'], 'verbose_name': 'Credit Note', 'verbose_name_plural': 'Credit Notes'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['invoice_reg_date'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
    ]
