# Generated by Django 5.2.1 on 2025-05-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('estandar', 'Usuario Estándar'), ('admin', 'Usuario Administrador')], max_length=10, verbose_name='Rol'),
        ),
    ]
